<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.8</TargetFramework>
    <!--<ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>-->
  </PropertyGroup>

  <ItemGroup>
    <None Update="TestData\cdf069b023ea4e33b5c78ac1eff45370.ultrasound-regions.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SemanticKernel.Abstractions\SemanticKernel.Abstractions.csproj" />
  </ItemGroup>
</Project>
